"""Write js/catalog.js from curriculum/map.md, level1.md, and level2.md."""
from pathlib import Path

root = Path(__file__).resolve().parents[1]
curriculum = root / "curriculum"


def table_rows(path, header_prefix):
    lines = path.read_text(encoding="utf-8").splitlines()
    start = next(i for i, line in enumerate(lines) if line.startswith(header_prefix))
    header = lines[start].split("\t")
    rows = []
    for line in lines[start + 1 :]:
        if not line.strip():
            continue
        if line.startswith("#"):
            break
        cells = line.split("\t")
        if len(cells) < len(header):
            cells += [""] * (len(header) - len(cells))
        rows.append(dict(zip(header, cells[: len(header)])))
    return rows


def js_string(value):
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    levels = table_rows(curriculum / "map.md", "id\tcode\t")
    abilities = table_rows(curriculum / "map.md", "id\ttext")
    items = []
    for level_id, filename in (("L1", "level1.md"), ("L2", "level2.md")):
        for row in table_rows(curriculum / filename, "id\ttrack\t"):
            row["level"] = level_id
            items.append(row)
    active_path = curriculum / "active.tsv"
    active = table_rows(active_path, "id\ttrack\t") if active_path.exists() else []

    lines = [
        "/* Generated by tools/build_catalog.py. Do not edit by hand. */",
        "window.CATALOG = {",
        "  levels: [",
    ]
    for row in levels:
        lines.append(
            "    { id: %s, code: %s, points: %s, requires: %s, title: %s },"
            % (
                js_string(row["id"]),
                js_string(row["code"]),
                js_string(row["points"]),
                js_string(row["requires"]),
                js_string(row["title"]),
            )
        )
    lines.append("  ],")
    lines.append("  abilities: [")
    for row in abilities:
        lines.append(
            "    { id: %s, text: %s }," % (js_string(row["id"]), js_string(row["text"]))
        )
    lines.append("  ],")
    lines.append("  items: [")
    for row in items:
        lines.append(
            "    { id: %s, level: %s, track: %s, ability: %s, bind: %s, deepens: %s, text: %s },"
            % (
                js_string(row["id"]),
                js_string(row["level"]),
                js_string(row["track"]),
                js_string(row["ability"]),
                js_string(row["bind"]),
                js_string(row["deepens"]),
                js_string(row["text"]),
            )
        )
    lines.append("  ],")
    lines.append("  active: [")
    for row in active:
        lines.append(
            "    { id: %s, track: %s, place: %s, text: %s },"
            % (
                js_string(row["id"]),
                js_string(row["track"]),
                js_string(row["place"]),
                js_string(row["text"]),
            )
        )
    lines.append("  ]")
    lines.append("};")
    lines.append("")
    out = root / "js" / "catalog.js"
    out.write_text("\n".join(lines), encoding="utf-8")
    print(
        "%s levels, %s abilities, %s items, %s active"
        % (len(levels), len(abilities), len(items), len(active))
    )


if __name__ == "__main__":
    main()
