"""Write js/catalog.js from curriculum tables, and the language reference pages."""
import html
from pathlib import Path

root = Path(__file__).resolve().parents[1]
curriculum = root / "curriculum"


def table_rows(path, header_prefix):
    lines = path.read_text(encoding="utf-8").splitlines()
    start = next(i for i, line in enumerate(lines) if line.startswith(header_prefix))
    header = lines[start].split("\t")
    rows = []
    for line in lines[start + 1 :]:
        if not line.strip():
            continue
        if line.startswith("#"):
            break
        cells = line.split("\t")
        if len(cells) < len(header):
            cells += [""] * (len(header) - len(cells))
        rows.append(dict(zip(header, cells[: len(header)])))
    return rows


def js_string(value):
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def split_list(value):
    if not value or not value.strip():
        return []
    return [part.strip() for part in value.split(";") if part.strip()]


def write_glossary():
    rows = table_rows(curriculum / "glossary.tsv", "id\tgroup\t")
    lines = [
        "/* Generated by tools/build_catalog.py. Do not edit by hand. */",
        "window.GLOSSARY = {",
        "  entries: [",
    ]
    for row in rows:
        aliases = ", ".join(js_string(part) for part in split_list(row.get("aliases", "")))
        also = ", ".join(js_string(part) for part in split_list(row.get("also", "")))
        stub = "true" if row.get("stub", "").strip().lower() == "yes" else "false"
        lines.append(
            "    { id: %s, group: %s, term: %s, aliases: [%s], brief: %s, body: %s, stub: %s, see: %s, also: [%s], page: %s, advanced: %s },"
            % (
                js_string(row["id"]),
                js_string(row["group"]),
                js_string(row["term"]),
                aliases,
                js_string(row.get("brief", "")),
                js_string(row.get("body", "")),
                stub,
                js_string(row.get("see", "")),
                also,
                js_string(row.get("page", "")),
                js_string(row.get("advanced", "")),
            )
        )
    lines.append("  ]")
    lines.append("};")
    lines.append("")
    (root / "js" / "glossary.js").write_text("\n".join(lines), encoding="utf-8")
    print("%s glossary" % len(rows))


def term_link(term_id, label):
    return (
        '<a class="term" data-term="%s" href="/#/glossary/%s" target="_blank" rel="noopener">%s</a>'
        % (html.escape(term_id), html.escape(term_id), html.escape(label))
    )


def ext_link(url, label):
    return '<a href="%s" target="_blank" rel="noopener">%s</a>' % (
        html.escape(url, quote=True),
        html.escape(label),
    )


def write_languages():
    """Three language pages share one frame, so the bodies are drawn from the table."""
    rows = table_rows(curriculum / "languages.tsv", "id\tterm\t")
    note = (
        "Generated by tools/build_catalog.py from curriculum/languages.tsv. "
        "Do not edit by hand."
    )
    letters = "abcd"
    labels = [row["label"] for row in rows]
    for index, row in enumerate(rows):
        steps = [part.strip() for part in row["outline"].split("|")]
        items = "\n".join("    <li>%s</li>" % html.escape(step) for step in steps if step)
        options = []
        for n, label in enumerate(labels):
            options.append(
                '      <label><input type="radio" name="q1" value="%s"> %s</label>'
                % (letters[n], html.escape(label))
            )
        options.append(
            '      <label><input type="radio" name="q1" value="d"> File endings only</label>'
        )
        page = """<!-- %s -->
<article class="lesson">
  <h2>%s</h2>
  <p>This page is a stub. It starts a minimal introduction to %s. The first step is written below. The later steps are an outline. The introduction ends with two places to continue.</p>
  <h3>The first step</h3>
  <p>%s %s</p>
  <h3>The rest of this mini introduction</h3>
  <p>These steps are the intended outline. They are not written out as lessons yet.</p>
  <ol>
%s
  </ol>
  <h3>Continue outside this course</h3>
  <p>A filled-in introduction still ends here. One link is an encyclopedia article. The other is a free course.</p>
  <ul>
    <li>%s</li>
    <li>%s</li>
  </ul>
  <p>The three languages are collected on <a href="/#/item/R.3">Languages</a>.</p>
  <h3>Check</h3>
  <p>Skip this if you already know the page.</p>
  <form class="quiz">
    <fieldset data-answer="%s">
      <legend>1. This page orients you to which language?</legend>
%s
    </fieldset>
    <fieldset data-answer="b">
      <legend>2. Besides the outline and the outward links, what is written here?</legend>
      <label><input type="radio" name="q2" value="a"> The whole free course</label>
      <label><input type="radio" name="q2" value="b"> The first step in getting oriented</label>
      <label><input type="radio" name="q2" value="c"> A second model</label>
      <label><input type="radio" name="q2" value="d"> The tools map</label>
    </fieldset>
    <fieldset data-answer="b">
      <legend>3. The end of this introduction links to which pair?</legend>
      <label><input type="radio" name="q3" value="a"> A usage meter and a CLI</label>
      <label><input type="radio" name="q3" value="b"> Wikipedia and a freeCodeCamp course</label>
      <label><input type="radio" name="q3" value="c"> The glossary only</label>
      <label><input type="radio" name="q3" value="d"> Two other models</label>
    </fieldset>
    <button type="submit">Check answers</button>
  </form>
</article>
""" % (
            note,
            html.escape(row["label"]),
            html.escape(row["label"]),
            term_link(row["term"], row["label"]),
            html.escape(row["first"]),
            items,
            ext_link(row["wiki"], "Wikipedia: " + row["label"]),
            ext_link(row["fcc"], row["fcc_label"]),
            letters[index],
            "\n".join(options),
        )
        (root / "content" / (row["id"] + ".html")).write_text(page, encoding="utf-8")

    body_rows = []
    for row in rows:
        body_rows.append(
            "      <tr><td>%s</td><td>%s</td><td><a href=\"/#/item/%s\">%s</a></td></tr>"
            % (
                html.escape(row["label"]),
                html.escape(row["blurb"]),
                html.escape(row["id"]),
                html.escape(row["id"]),
            )
        )
    parent = """<!-- %s -->
<article class="lesson">
  <h2>Languages</h2>
  <p>This page collects three minimal introductions. Each one is a stub: the first step is written, the rest is an outline, and the page ends with links to a longer free course and to Wikipedia.</p>
  <p>Three languages come up in the basic work of this course. %s is the markup of a page. %s is what a browser can run after the page is open. %s is a file of steps a helper can run.</p>
  <p>Another lesson can name one of these in a sentence and open the page in a new tab, so the lesson stays put.</p>
  <table>
    <thead>
      <tr><th>Language</th><th>In this course</th><th>Page</th></tr>
    </thead>
    <tbody>
%s
    </tbody>
  </table>
  <h3>Check</h3>
  <p>Skip this if you already know the page.</p>
  <form class="quiz">
    <fieldset data-answer="b">
      <legend>1. This page collects which set?</legend>
      <label><input type="radio" name="q1" value="a"> Grok, ChatGPT, Claude, and Gemini</label>
      <label><input type="radio" name="q1" value="b"> HTML, JavaScript, and Python</label>
      <label><input type="radio" name="q1" value="c"> Only file endings</label>
      <label><input type="radio" name="q1" value="d"> The usage clocks</label>
    </fieldset>
    <fieldset data-answer="c">
      <legend>2. A lesson elsewhere opens one of these language pages how?</legend>
      <label><input type="radio" name="q2" value="a"> By replacing the model</label>
      <label><input type="radio" name="q2" value="b"> By pasting the whole language into the lesson</label>
      <label><input type="radio" name="q2" value="c"> With a link that opens the language page in a new tab</label>
      <label><input type="radio" name="q2" value="d"> Only after ARTI2000X is finished</label>
    </fieldset>
    <fieldset data-answer="a">
      <legend>3. Each language page currently holds which of these?</legend>
      <label><input type="radio" name="q3" value="a"> A first step, an outline of the rest, and outward links</label>
      <label><input type="radio" name="q3" value="b"> A complete programming course</label>
      <label><input type="radio" name="q3" value="c"> Only a Wikipedia article</label>
      <label><input type="radio" name="q3" value="d"> The tools map</label>
    </fieldset>
    <button type="submit">Check answers</button>
  </form>
</article>
""" % (
        note,
        term_link("html", "HTML"),
        term_link("javascript", "JavaScript"),
        term_link("python", "Python"),
        "\n".join(body_rows),
    )
    (root / "content" / "R.3.html").write_text(parent, encoding="utf-8")
    print("%s language pages" % (len(rows) + 1))


def main():
    levels = table_rows(curriculum / "map.md", "id\tcode\t")
    abilities = table_rows(curriculum / "map.md", "id\ttext")
    items = []
    for level_id, filename in (("L1", "level1.md"), ("L2", "level2.md")):
        for row in table_rows(curriculum / filename, "id\ttrack\t"):
            row["level"] = level_id
            items.append(row)
    active_path = curriculum / "active.tsv"
    active = table_rows(active_path, "id\ttrack\t") if active_path.exists() else []
    reference_path = curriculum / "reference.tsv"
    reference = table_rows(reference_path, "id\ttrack\t") if reference_path.exists() else []
    tools_path = curriculum / "tools.tsv"
    tools = table_rows(tools_path, "id\tgroup\t") if tools_path.exists() else []
    fresh_path = curriculum / "freshness.tsv"
    freshness = table_rows(fresh_path, "id\tadded\t") if fresh_path.exists() else []

    lines = [
        "/* Generated by tools/build_catalog.py. Do not edit by hand. */",
        "window.CATALOG = {",
        "  levels: [",
    ]
    for row in levels:
        lines.append(
            "    { id: %s, code: %s, points: %s, requires: %s, title: %s },"
            % (
                js_string(row["id"]),
                js_string(row["code"]),
                js_string(row["points"]),
                js_string(row["requires"]),
                js_string(row["title"]),
            )
        )
    lines.append("  ],")
    lines.append("  abilities: [")
    for row in abilities:
        lines.append(
            "    { id: %s, text: %s }," % (js_string(row["id"]), js_string(row["text"]))
        )
    lines.append("  ],")
    lines.append("  items: [")
    for row in items:
        lines.append(
            "    { id: %s, level: %s, track: %s, ability: %s, bind: %s, deepens: %s, text: %s },"
            % (
                js_string(row["id"]),
                js_string(row["level"]),
                js_string(row["track"]),
                js_string(row["ability"]),
                js_string(row["bind"]),
                js_string(row["deepens"]),
                js_string(row["text"]),
            )
        )
    lines.append("  ],")
    lines.append("  active: [")
    for row in active:
        lines.append(
            "    { id: %s, track: %s, place: %s, text: %s },"
            % (
                js_string(row["id"]),
                js_string(row["track"]),
                js_string(row["place"]),
                js_string(row["text"]),
            )
        )
    lines.append("  ],")
    lines.append("  reference: [")
    for row in reference:
        lines.append(
            "    { id: %s, track: %s, place: %s, text: %s },"
            % (
                js_string(row["id"]),
                js_string(row["track"]),
                js_string(row["place"]),
                js_string(row["text"]),
            )
        )
    lines.append("  ],")
    lines.append("  tools: [")
    for row in tools:
        lines.append(
            "    { id: %s, group: %s, title: %s, track: %s, place: %s, text: %s },"
            % (
                js_string(row["id"]),
                js_string(row["group"]),
                js_string(row["title"]),
                js_string("reference"),
                js_string(row["group"]),
                js_string(row["text"]),
            )
        )
    lines.append("  ],")
    lines.append("  freshness: {")
    for row in freshness:
        lines.append(
            "    %s: { added: %s, updated: %s },"
            % (
                js_string(row["id"]),
                js_string(row.get("added", "")),
                js_string(row.get("updated", "")),
            )
        )
    lines.append("  },")
    span_path = curriculum / "gradespan.tsv"
    spans = table_rows(span_path, "id\tfloor\t") if span_path.exists() else []
    lines.append("  gradespan: {")
    for row in spans:
        lines.append(
            "    %s: { floor: %s, ceiling: %s, kind: %s },"
            % (
                js_string(row["id"]),
                js_string(row.get("floor", "")),
                js_string(row.get("ceiling", "")),
                js_string(row.get("kind", "")),
            )
        )
    lines.append("  }")
    lines.append("};")
    lines.append("")
    out = root / "js" / "catalog.js"
    out.write_text("\n".join(lines), encoding="utf-8")
    write_glossary()
    write_languages()
    print(
        "%s levels, %s abilities, %s items, %s active, %s reference, %s tools, %s freshness"
        % (
            len(levels),
            len(abilities),
            len(items),
            len(active),
            len(reference),
            len(tools),
            len(freshness),
        )
    )


if __name__ == "__main__":
    main()
